# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("https://www.buhl.de/")
    self.driver.find_element(By.CSS_SELECTOR, ".default > .account-text").click()
    self.driver.find_element(By.ID, "eml-user-login").send_keys("s-c-h-m-i-t-t@web.de")
    self.driver.find_element(By.ID, "psw-user-login").send_keys(".w77j08uni!")
    self.driver.find_element(By.ID, "form-login-submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".schnellzugriffe-box:nth-child(3) span").click()
    self.driver.find_element(By.ID, "select-rechnung").click()
    self.driver.find_element(By.CSS_SELECTOR, ".documents-document-box:nth-child(1) .nodeco:nth-child(1) .documents-document-box-entry-text-title").click()
  
