# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestKabelTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_kabelTest(self):
    self.driver.get("https://www.vodafone.de/meinvodafone/account/login")
    self.driver.find_element(By.CSS_SELECTOR, ".fm-field-container > #txtUsername").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fm-field-container > #txtUsername").send_keys("StefanSchmittMalin")
    self.driver.find_element(By.CSS_SELECTOR, ".fm-field-container > #txtPassword").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fm-field-container > #txtPassword").send_keys(".K77j08uni!")
    self.driver.find_element(By.CSS_SELECTOR, ".fm-field-container > #txtPassword").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2) > .title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ws10-hybrid-table__row-desktop:nth-child(1) .ws10-hybrid-table__icon-holder:nth-child(2) > .ws10-hybrid-table__icon").click()
  
